
###

### GET /
GET http://localhost:5000

### Register a user POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json


{
    "username": "mariamayskaya@mail.ru",
    "password": "123456"
}

### Login a user POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json


{
    "username": "mariamayskaya@mail.ru",
    "password": "123456"
}

### Fetch all todos GET /TODOS (protected)
GET http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NDEzOTM0LCJleHAiOjE3NDY1MDAzMzR9.EyiBZw-Q0ZD6S1s9RcMlbVKUp9l_oWXJQyDj1vn8w5k

### Creates a new todo POST /TODOS (protected)
POST http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NDEzOTM0LCJleHAiOjE3NDY1MDAzMzR9.EyiBZw-Q0ZD6S1s9RcMlbVKUp9l_oWXJQyDj1vn8w5k
Content-Type: application/json 

{
    "task": "Finish coding the projects"
}

### Update a todo PUT /TODOS/:ID (protected)
PUT http://localhost:5000/todos/2?page=4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NDEzOTM0LCJleHAiOjE3NDY1MDAzMzR9.EyiBZw-Q0ZD6S1s9RcMlbVKUp9l_oWXJQyDj1vn8w5k
Content-Type: application/json

{
    "completed": 1
}

### Delete a todo DELETE /TODOS/:ID (protected)
DELETE http://localhost:5003/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NDEzOTM0LCJleHAiOjE3NDY1MDAzMzR9.EyiBZw-Q0ZD6S1s9RcMlbVKUp9l_oWXJQyDj1vn8w5kmariavergaraa@mail.com